# Generated by Django 3.2.9 on 2021-12-12 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
